title: Welcome to my website
author: Palash
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  site description

# social links
twitter_username: palash639 # DO NOT include the @ character, or else the build will fail!
github_username:  palashcode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
